import "./globals.css";
import type { Metadata } from "next";
import { Inter, Wix_Madefor_Text } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const wix_Madefor_Text = Wix_Madefor_Text({
  subsets: ["latin"],
  variable: "--sans-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={wix_Madefor_Text.variable}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
